{% set name = "tango-admin" %}
{% set version = "1.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/tango_admin/-/releases/Release_{{ version }}/downloads/tango_admin-with-submodules-Release_{{ version }}.tar.gz
  sha256: aa24d6fd7703f866832065cde828620db2dff7e9103c97c0d0a1c9ea49ef0f56

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # tango_admin --help returns -EINVAL
    - tango_admin --help 2>&1 | grep Usage

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango database command line interface
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This utility is a Tango database command line interface.
    Obviously, not all the database features are interfaced by this tool.
  dev_url: https://gitlab.com/tango-controls/tango_admin

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
