{% set name = "tango-admin" %}
{% set version = "1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/tango_admin/-/archive/Release_{{ version }}/tango_admin-Release_{{ version }}.tar.gz
  sha256: 2af2e2c6c9d125c51dcaf5a201b7a2224c6c59c74d741e99967cd9b88fb414e8

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
    - libtool
    - pkg-config
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # tango_admin --help returns -EINVAL
    - tango_admin --help 2>&1 | grep Usage

about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango database command line interface
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This utility is a Tango database command line interface.
    Obviously, not all the database features are interfaced by this tool.
  dev_url: https://gitlab.com/tango-controls/tango_admin

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
