{% set name = "tango-admin" %}
{% set version = "1.26" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/tango-controls/tango_admin/-/releases/Release_{{ version }}/downloads/tango_admin-with-submodules-Release_{{ version }}.tar.gz
  sha256: 7ac9c89500235c85b8d4ad05c94947f23c1f8a05d0533e2f8996bef5ecdbf1d7

build:
  number: 0

requirements:
  build:
    - cmake
    - make                  # [unix]
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - pkg-config            # [unix]
  host:
    - cppzmq
    - cpptango
    - omniorb-libs

test:
  commands:
    # tango_admin --help returns -EINVAL
    - tango_admin --help 2>&1 | grep Usage     # [unix]
    - tango_admin --help 2>&1 | findstr Usage  # [win]


about:
  home: https://www.tango-controls.org
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango database command line interface
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This utility is a Tango database command line interface.
    Obviously, not all the database features are interfaced by this tool.
  dev_url: https://gitlab.com/tango-controls/tango_admin

extra:
  recipe-maintainers:
    - beenje
    - bourtemb
