schema_version: 1

context:
  version: "1.28"

recipe:
  name: tango-admin-split
  version: ${{ version }}

source:
  url: https://gitlab.com/tango-controls/tango_admin/-/releases/Release_${{ version }}/downloads/tango_admin-with-submodules-Release_${{ version }}.tar.gz
  sha256: 02159745d2a7c738483630788a36ebf92a311f29ce06c6202201813fc09224e1

build:
  number: 2

outputs:
  - staging:
      name: tango-admin-build
    requirements:
      build:
        - cmake
        - ninja
        - if: unix
          then:
            - pkg-config
        - ${{ stdlib('c') }}
        - ${{ compiler('cxx') }}
      host:
        - cppzmq
        - cpptango
        - omniorb-libs
    build:
      script:
        file: build

  - package:
      name: tango-admin
    inherit: tango-admin-build
    build:
      files:
        - if: unix
          then:
            - bin/tango_admin
          else:
            - Library/bin/tango_admin.exe
    tests:
      - script:
          - tango_admin --help

  - package:
      name: tango-admin-dbg
    inherit:
      from: tango-admin-build
      run_exports: false
    build:
      skip:
        - not linux
      dynamic_linking:
        # Prevent dbg file to be modified
        # Will raise CRC mismatch otherwise!
        binary_relocation: false
      files:
        - lib/debug/tango_admin.dbg
    requirements:
      run:
        - ${{ pin_subpackage('tango-admin', exact=True) }}
    tests:
      - package_contents:
          files:
            - lib/debug/tango_admin.dbg

about:
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: Tango database command line interface
  description: |
    Tango-Controls is a software toolkit for building control systems.
    This utility is a Tango database command line interface.
    Obviously, not all the database features are interfaced by this tool.
  homepage: https://www.tango-controls.org
  repository: https://gitlab.com/tango-controls/tango_admin

extra:
  feedstock-name: tango-admin
  recipe-maintainers:
    - beenje
    - bourtemb
